services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.5.1
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: true
      KC_PROXY_ADDRESS_FORWARDING: true
      KC_FEATURES: preview
    ports:
      - "8002:8080"
    command: start-dev