spring:
  application:
    name: gateway
  management:
    endpoints:
      web:
        exposure:
          include: health
    endpoint:
      health:
        probes:
          enabled: true
        show-details: always
  security:
    oauth2:
      client:
        registration:
          gateway-rest-api:
            client-id: api-gateway-client
            client-secret: ${GATEWAY_CLIENT_SECRET:TqOwvN7EBjXbX4ymF7v9VV3IftfbcpjM}
            scope:
              - openid
              - profile
              - email
              - user:read
              - user:write
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          gateway-rest-api:
            # Use the Docker service name 'keycloak' and internal port 8080
            issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8002/realms/intwork}
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8002/realms/intwork}
server:
  port: 9090

